apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-new
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test-new
  template:
    metadata:
      labels:
        app: nginx-test-new
    spec:
      containers:
      - name: nginx-test-new
        image: nginx:1.21.0-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-new
  namespace: test
spec:
  type: NodePort
  selector:
    app: nginx-test-new
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
